galaxy_info:
  author: Fabio Rizzi
  description: Personal customizations
  company: None
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - 19.10
  galaxy_tags:
    - ubuntu
    - eoan
    - fabiodbr
    - desktop
dependencies:
  - src: https://github.com/gantsign/ansible-role-visual-studio-code-extensions
    when: '"ide" is defined and "ide" in install'
